### ISSUE TITLE
Update to new BepInEx builds

### ISSUE THREAD

**Issue by limoka** [xiaoye97/CoreKeeperAutoFish#3]
Recently our community have updated to new Bleeding Edge BepInEx releases, which contain breaking changes. 
Can you please update your mod to work with this new BepInEx?

**Comment by xiaoye97** [comment]
Is it Bleeding Edge 656? I will update it.

**Comment by xiaoye97** [comment]
Now update.

**Comment by limoka** [comment]
Don't forget to upload that to Thunderstore.
